// Synthetic API models server ID normalization. Never contacts production.
import http from 'node:http';import fs from 'node:fs/promises';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const blank=()=>({properties:[],tenants:[],contracts:[],payments:[],credits:[],maintenance:[],insurance:[],agenda:[]});let state=blank(),revision=0,role='Administrador',calls=[],failDelete=false;
const runner=String.raw`<!doctype html><meta charset="utf-8"><title>Validación de inmuebles</title><h1>Validación de inmuebles</h1><pre>Ejecutando…</pre><iframe style="width:390px;height:844px"></iframe><script type="module">
const frame=document.querySelector('iframe'),out=document.querySelector('pre'),lines=[],doc=()=>frame.contentDocument,el=s=>doc().querySelector(s);
const check=(v,m)=>{if(!v)throw Error(m)},pass=m=>{lines.push('PASS '+m);out.textContent=lines.join('\n')};
const wait=async(f)=>{for(let i=0;i<140;i++){if(await f())return;await new Promise(r=>setTimeout(r,50))}throw Error('Timeout '+f)};
const config=async(data)=>fetch('/test-config',{method:'POST',body:JSON.stringify(data)}).then(r=>r.json()),status=()=>fetch('/test-status').then(r=>r.json());
const load=async(before=false)=>{frame.src='/?baseline='+(before?'1':'0')+'&r='+Math.random();await new Promise(r=>frame.onload=r);frame.contentWindow.alert=m=>lines.push('ALERT '+m);await wait(()=>el('#authForm')?.onsubmit);el('#authEmail').value='test@example.invalid';el('#authPassword').value='Synthetic-password-123';el('#authForm').requestSubmit();await wait(()=>!doc().body.classList.contains('access-locked'))};
const openList=()=>el('nav button[data-v="inmuebles"]').click();
const create=async(name)=>{openList();el('#newProp').click();el('[name="name"]').value=name;el('[name="rent"]').value='10000';el('[name="start"]').value='2026-09-01';el('[name="end"]').value='2027-09-30';el('#form').requestSubmit();await wait(()=>el('#cloudState').textContent.includes('Nube'))};
try{
await config({reset:true});await load(true);await create('Reproducción anterior');el('#deleteProperty').click();check(!el('#deleteEntityDialog'),'Fallo original no reproducido');pass('Reproducido: Eliminar no abre tras sincronizar');check(!el('#detail').textContent.includes('2027-09-30'),'Fecha anterior inesperada');pass('Reproducido: vencimiento sin inquilino descartado');
await config({reset:true});await load();await create('Prueba A');check(el('#detail').textContent.includes('2027-09-30'),'fecha no visible');el('#ep').click();check(el('#modal').classList.contains('on'),'Editar no abre');check(el('[name="end"]').value==='2027-09-30','fecha no conservada');el('#cancel').click();pass('Alta, sincronización y edición conservan fecha e identificador');
await load();openList();check(el('#props').textContent.includes('2027-09-30'),'fecha falta en lista tras recarga');el('#props [data-p]').click();el('#ep').click();el('[name="end"]').value='2028-10-15';el('#form').requestSubmit();await wait(()=>el('#cloudState').textContent.includes('Nube'));pass('Vencimiento editable después de recargar');
await create('Prueba B');const b=(await status()).state.properties.find(p=>p.name==='Prueba B').id;el('#deleteProperty').click();check(el('#deleteEntityDialog').textContent.includes('Prueba B'),'inmueble equivocado');check(el('#deleteEntityDialog').textContent.includes('conservarán'),'no explica historial');el('#cancelEntityDeletion').click();check(!(await status()).calls.some(x=>x.method==='DELETE'),'Cancelar envió DELETE');pass('Confirmación explícita nombra el inmueble; cancelar no elimina');
await config({failDelete:true});el('#deleteProperty').click();el('#confirmEntityDeletion').click();await wait(()=>el('#deleteEntityMessage').textContent.includes('Error simulado'));check(!el('#confirmEntityDeletion').disabled,'sin reintento');check(!(await status()).state.properties.find(x=>x.id===b).archivedAt,'error eliminó registro');await config({failDelete:false});el('#confirmEntityDeletion').click();await wait(()=>!el('#deleteEntityDialog'));check(!el('#props').textContent.includes('Prueba B'),'sigue activo');check(el('#props').textContent.includes('Prueba A'),'eliminó otro');pass('Error visible y reintento; solo archiva el inmueble confirmado');
await load();openList();check(!el('#props').textContent.includes('Prueba B'),'reaparece al recargar');check(el('#props').textContent.includes('2028-10-15'),'fecha editada no persistió');pass('Eliminación y fecha persisten después de recargar/sincronizar');
await config({role:'Consulta'});await load();openList();el('#props [data-p]').click();check(!el('#ep')&&!el('#deleteProperty'),'Consulta puede editar/eliminar');pass('Consulta conserva restricciones');pass('TODAS LAS PRUEBAS COMPLETADAS');
}catch(e){out.textContent=lines.join('\n')+'\nFAIL '+e.message}
</script>`;
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),chunks=[];for await(const c of req)chunks.push(c);const data=chunks.length?JSON.parse(Buffer.concat(chunks)):{};const send=(body,code=200)=>{res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(body))};
if(url.pathname==='/test-status')return send({state,calls});if(url.pathname==='/test-config'){if(data.reset){state=blank();revision=0;calls=[];role='Administrador'}if(data.role)role=data.role;if('failDelete'in data)failDelete=data.failDelete;return send({ok:true})}
if(url.pathname==='/test-runner'){res.writeHead(200,{'Content-Type':'text/html'});return res.end(runner)}if(url.pathname==='/api/auth')return send({ok:true,user:{id:'test-user',email:'test@example.invalid',role}});
if(url.pathname==='/api/state'){calls.push({method:req.method,id:data.id});if(req.method!=='GET'&&data.revision!==String(revision))return send({error:'La información cambió'},409);
if(req.method==='PUT'){state=structuredClone(data.state);const map=new Map();for(const k of ['properties','tenants','contracts'])for(const x of state[k]){const old=x.id;if(!/^[0-9a-f-]{36}$/.test(old)){x.id=crypto.randomUUID();map.set(old,x.id)}}for(const c of state.contracts){c.propertyId=map.get(c.propertyId)||c.propertyId;c.tenantId=map.get(c.tenantId)||c.tenantId}revision++}
if(req.method==='DELETE'){if(failDelete)return send({error:'Error simulado: relación protegida'},409);if(!['Administrador','Cobranza'].includes(role))return send({error:'Sin permiso'},403);const p=state.properties.find(x=>x.id===data.id);if(!p)return send({error:'No existe'},404);p.archivedAt=new Date().toISOString();revision++}return send({ok:true,state,revision:String(revision),user:{id:'test-user',role}})}
if(url.pathname.startsWith('/api/'))return send({documents:[],users:[]});const name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));if(!['index.html','fiscal.js','insurance-fields.js','BAL INTRERNATIONAL.png'].includes(name))return send({},404);res.writeHead(200,{'Content-Type':name.endsWith('.html')?'text/html':name.endsWith('.js')?'text/javascript':'image/png'});res.end(url.searchParams.get('baseline')==='1'&&name==='index.html'?execFileSync('git',['show','HEAD:index.html'],{cwd:new URL('..',import.meta.url)}):await fs.readFile(new URL('../'+name,import.meta.url)))});
server.listen(0,'127.0.0.1',()=>console.log('TEST URL http://127.0.0.1:'+server.address().port+'/test-runner'));
