// Test production functions with a query double. This does not replace live Neon integration.
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import crypto from 'node:crypto';
let src=await fs.readFile(new URL('../api/state.js',import.meta.url),'utf8');
for(const [specifier,path] of [['../insurance-fields.js','../insurance-fields.js'],['../fiscal.js','../fiscal.js'],['pg','../node_modules/pg/lib/index.js']])src=src.replace(`from "${specifier}"`,`from "${new URL(path,import.meta.url).href}"`);
src+='\nexport {normalizePropertyDates,normalized,readState,replaceState,deleteEntity,permissionError,pool};';
const api=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const empty={properties:[],tenants:[],contracts:[],payments:[],credits:[],maintenance:[],insurance:[],agenda:[]};
const dates={start:'2026-09-01',end:'2027-09-30',dueDay:5};
assert.deepEqual(api.normalizePropertyDates({dueDay:5,end:dates.end,start:dates.start}),dates);
for(const d of [{end:'2026-02-30'},{start:'2027-01-01',end:'2026-01-01'},{end:'invalid'}])assert.throws(()=>api.normalizePropertyDates(d),e=>e.status===400);
console.log('PASS valid dates, calendar rejection and canonical JSONB order');
const pid=crypto.randomUUID(),user={id:crypto.randomUUID(),role:'Administrador'},property={id:pid,name:'Synthetic property',rent:100,deposit:0,status:'Disponible',contractDraft:dates};
let calls=[];const client={query:async(sql,params)=>{calls.push({sql,params});return {rows:[]}}};
await api.replaceState(client,{...empty,properties:[property]},user,empty);
const insert=calls.find(x=>x.sql.startsWith('insert into properties'));assert.equal(insert.params[0],pid);
const audit=calls.find(x=>x.sql.includes("'property_dates'"));assert.equal(audit.params[1],pid);assert.deepEqual(audit.params[2],dates);
assert(!calls.some(x=>x.sql.startsWith('insert into contracts')));assert(!calls.some(x=>/^delete from (properties|tenants)/.test(x.sql)));
console.log('PASS UUID preserved; dates persist without creating a contract or deleting property/tenant rows');
calls=[];const canonical=api.normalized({...empty,properties:[property]});await api.replaceState(client,canonical,user,canonical);assert(!calls.some(x=>x.sql.includes("'property_dates'")));console.log('PASS unchanged dates do not produce duplicate audit entries');
const state=await api.readState({query:async sql=>({rows:sql.includes('from properties e')?[{id:pid,name:'Synthetic property',rent:100,deposit:0,status:'Disponible',contract_draft:{dueDay:5,end:dates.end,start:dates.start}}]:[]})});
assert.deepEqual(state.properties[0].contractDraft,dates);assert.equal(api.permissionError('Consulta',state,structuredClone(state)),null);
const changed=structuredClone(state);changed.properties[0].contractDraft.end='2029-01-01';assert(api.permissionError('Consulta',state,changed));assert(api.permissionError('Mantenimiento',state,changed));assert.equal(api.permissionError('Cobranza',state,changed),null);
console.log('PASS dates returned by API; Consulta/Mantenimiento cannot modify; existing Cobranza rights preserved');
const cid=crypto.randomUUID(),tid=crypto.randomUUID();calls=[];
const archiveDb={query:async(sql,params)=>{calls.push({sql,params});if(sql==='select * from properties where id=$1 for update')return{rows:[{id:pid,name:'Synthetic property'}]};if(sql==='select * from contracts where property_id=$1 for update')return{rows:[{id:cid,property_id:pid,tenant_id:tid,status:'Vigente',end_date:'2027-09-30'}]};return{rows:[]}}};
for(const role of ['Consulta','Mantenimiento'])await assert.rejects(api.deleteEntity(archiveDb,{entity:'property',id:pid},{...user,role}),e=>e.status===403);
await api.deleteEntity(archiveDb,{entity:'property',id:pid},user);
assert(!calls.some(x=>/^delete /i.test(x.sql)));assert(calls.some(x=>x.sql.startsWith('update contracts')&&x.params[0]===cid));assert(calls.some(x=>x.sql.startsWith('insert into audit_log')&&x.params[1]==='property'&&x.params[2]===pid));
assert(!calls.some(x=>/^(update|delete from) (payments|credits|tenants|property_documents|insurance_policies|insurance_documents|maintenance_tasks)/.test(x.sql)));
console.log('PASS archive selects exact ID; closes linked contract and leaves financial, document, insurance and maintenance history untouched');
await assert.rejects(api.deleteEntity(client,{entity:'property',id:'temporary-id'},user),e=>e.status===400);
await api.pool.end();console.log('PASS API checks completed with query doubles (Neon integration still required)');
